### ISSUE TITLE
Laminate with resin-free layers

### ISSUE THREAD

**Issue by cpivot** [rsmith-nl/lamprop#1]
Hi, 
First of all, your library seems to be very interesting. But here a quick how-to question : 
If I want to get the stiffness matrix of the following materials : 

wood A 10mm thick (without fiber)
fiber 1 1mm thick (with resin)
wood B 5mm thick (without fiber)
fiber 1 1mm thick (with resin)
wood C 5mm thick (withtout resin)

How can I proceed with your code?
Best
Charles

**Comment by rsmith-nl** [comment]
On Thu, Feb 14, 2019 at 11:43:56PM -0800, Charles Pivot wrote:
>  Hi,
>  First of all, your library seems to be very interesting. But here a quick how-to question :
>  If I want to get the stiffness matrix of the following materials :
> 
>  wood A 10mm thick (without fiber)
>  fiber 1 1mm thick (with resin)
>  wood B 5mm thick (without fiber)
>  fiber 1 1mm thick (with resin)
>  wood C 5mm thick (withtout resin)
> 
>  How can I proceed with your code?

That's an interesting question!

Keep in mind that lamprop assumes that lamina are transversely isotropic. Wood
on the other hand exhibits polar orthotropy. So don't expect the calculation
to yield perfect results. Depending on how the wood is sawn and laid, you
might get curvatures that are not predicted by the calculations.

What I would suggest is to define "fiber" and "resin" types that together mimic
the Young's Moduli of wood in the longitudinal and radial or tangential
directions, and use that for the wood layers.

One thing to keep in mind that the mechanical properties of wood depend very much on
its density which can vary considerably. The moisture content also has
significant influence on the mechanical properties.


Hope this helps.

Roland
-- 
R.F.Smith                                   http://rsmith.home.xs4all.nl/
[plain text email much appreciated]         https://github.com/rsmith-nl/
